/**
 * Template document.
 *
 * A template is a canvas, a framing spec, and a stack of layers. The framing
 * spec is the part that distinguishes this from a generic design tool: the
 * product image is not a layer you position, it is a *subject* the canvas
 * frames according to landmarks (see `src/framing/`). Everything else — text,
 * logos, overlays — is drawn on top in ordinary percentage coordinates.
 *
 * Layer geometry is in PERCENT of canvas size, never pixels, so one template
 * renders correctly at 1080×1350 and at 2048×2560 without change.
 *
 * Isomorphic: types and defaults only, no runtime dependencies.
 */

import type { AnchorName } from '@/vision/types'
import type { FramingSpec } from '@/framing/types'
import { clonePreset, DEFAULT_FRAMING_PRESET } from '@/framing/types'

// ─── Canvas ──────────────────────────────────────────────────────────────────

export type AspectRatioId = '1:1' | '4:5' | '2:3' | '3:4' | '9:16' | '16:9' | '1.91:1' | 'custom'

export interface AspectRatioPreset {
  id: AspectRatioId
  label: string
  width: number
  height: number
}

export const ASPECT_RATIOS: AspectRatioPreset[] = [
  { id: '1:1', label: 'Square 1:1', width: 1080, height: 1080 },
  { id: '4:5', label: 'Portrait 4:5', width: 1080, height: 1350 },
  { id: '2:3', label: 'Portrait 2:3', width: 1200, height: 1800 },
  { id: '3:4', label: 'Portrait 3:4', width: 1200, height: 1600 },
  { id: '9:16', label: 'Story 9:16', width: 1080, height: 1920 },
  { id: '16:9', label: 'Landscape 16:9', width: 1920, height: 1080 },
  { id: '1.91:1', label: 'Wide 1.91:1', width: 1200, height: 628 },
]

export type BackgroundMode =
  /** Flat colour. */
  | 'solid'
  /** Two-stop linear gradient. */
  | 'gradient'
  /**
   * Blurred, scaled copy of the source filling the canvas behind the subject.
   * Only visible where the crop overflows the source or the subject is
   * letterboxed — which is exactly when a flat colour looks wrong.
   */
  | 'blur_extend'
  /** Edge-clamped stretch of the source's border pixels. Cheaper than blur. */
  | 'edge_extend'
  /**
   * AI-outpainted extension of the source's own studio environment —
   * backdrop, lighting, floor — generated by the self-hosted inpaint service
   * (`services/inpaint-service`) and cached per (photo, framing, prompt).
   * Only different from `edge_extend` where the crop actually overflows the
   * source. Never falls back to a plain fill silently on failure — a
   * `background_fill` job failure is a distinct, surfaced, retryable job
   * state (see `src/jobs/worker.ts`), not something a render papers over.
   */
  | 'ai_extend'

export interface BackgroundSettings {
  mode: BackgroundMode
  color: string
  gradientFrom: string
  gradientTo: string
  /** Degrees, 0 = top-to-bottom. */
  gradientAngle: number
  /** 0–60px at canvas scale. */
  blurRadius: number
  /** How far the blurred copy is zoomed past the frame, 1.0–1.6. */
  blurZoom: number
  /**
   * `ai_extend` only. Tells the inpaint service what is ACTUALLY in frame —
   * left empty, a generic backdrop-agnostic prompt is used instead (see
   * `DEFAULT_PROMPT` in `services/inpaint-service`). Worth setting per
   * template to name the real backdrop (a specific studio rig, a particular
   * set) — a prompt written for one backdrop, applied to a photo shot
   * against a different one, does not fail quietly: it invents equipment
   * that was never there.
   */
  backdropPrompt: string
}

export const DEFAULT_BACKGROUND: BackgroundSettings = {
  mode: 'solid',
  color: '#ffffff',
  gradientFrom: '#f4f4f5',
  gradientTo: '#d4d4d8',
  gradientAngle: 160,
  blurRadius: 28,
  blurZoom: 1.15,
  backdropPrompt: '',
}

// ─── Layers ──────────────────────────────────────────────────────────────────

export type LayerType = 'text' | 'image' | 'rectangle' | 'ellipse' | 'badge'

export interface BaseLayer {
  id: string
  type: LayerType
  name: string
  /** All four are percentages of canvas size, 0–100. */
  x: number
  y: number
  width: number
  height: number
  rotation: number
  opacity: number
  zIndex: number
  visible: boolean
  locked: boolean
  /**
   * Pin this layer to a landmark instead of a fixed canvas position.
   *
   * When set, x/y are treated as an OFFSET (in canvas percent) from where the
   * anchor landed after framing. A "NEW IN" badge pinned to `shoulder_right`
   * follows the model's shoulder across a catalog instead of sitting at a fixed
   * spot that sometimes lands on her face.
   */
  anchorTo: AnchorName | null
}

export type TextAlign = 'left' | 'center' | 'right'

export interface TextLayer extends BaseLayer {
  type: 'text'
  /** Supports {{variables}} — see `resolveTemplateVariables`. */
  content: string
  fontFamily: string
  /** Percentage of canvas height, so text scales with the canvas. */
  fontSizePct: number
  fontWeight: 'normal' | 'bold'
  color: string
  align: TextAlign
  lineHeight: number
  letterSpacing: number
  /** Wrap at the layer's width rather than overflowing. */
  wrap: boolean
  backgroundColor: string | null
  paddingPct: number
  borderRadiusPct: number
  uppercase: boolean
}

export interface ImageLayer extends BaseLayer {
  type: 'image'
  /** Storage key under the `assets` media root. */
  assetKey: string
  fit: 'contain' | 'cover' | 'fill'
  borderRadiusPct: number
}

export interface RectangleLayer extends BaseLayer {
  type: 'rectangle'
  fill: string
  borderRadiusPct: number
  strokeColor: string | null
  strokeWidthPct: number
}

export interface EllipseLayer extends BaseLayer {
  type: 'ellipse'
  fill: string
  strokeColor: string | null
  strokeWidthPct: number
}

export interface BadgeLayer extends BaseLayer {
  type: 'badge'
  content: string
  fill: string
  color: string
  fontFamily: string
  fontSizePct: number
  fontWeight: 'normal' | 'bold'
  shape: 'pill' | 'rectangle' | 'circle'
  uppercase: boolean
}

export type Layer = TextLayer | ImageLayer | RectangleLayer | EllipseLayer | BadgeLayer

// ─── Document ────────────────────────────────────────────────────────────────

export const TEMPLATE_SCHEMA_VERSION = 1

export interface TemplateDocument {
  schemaVersion: number
  canvas: {
    width: number
    height: number
    aspectRatio: AspectRatioId
  }
  background: BackgroundSettings
  framing: FramingSpec
  layers: Layer[]
  /**
   * Draw the subject beneath the layer stack at this z-index. Layers with a
   * lower zIndex render behind the photo — how a full-bleed background graphic
   * is expressed.
   */
  subjectZIndex: number
}

export function createDefaultTemplate(aspectRatioId: AspectRatioId = '4:5'): TemplateDocument {
  const preset = ASPECT_RATIOS.find(a => a.id === aspectRatioId) ?? ASPECT_RATIOS[1]
  return {
    schemaVersion: TEMPLATE_SCHEMA_VERSION,
    canvas: { width: preset.width, height: preset.height, aspectRatio: preset.id },
    background: { ...DEFAULT_BACKGROUND },
    framing: clonePreset(DEFAULT_FRAMING_PRESET),
    layers: [],
    subjectZIndex: 0,
  }
}

// ─── Variables ───────────────────────────────────────────────────────────────

/**
 * Text substitutions available in text and badge layers.
 *
 * Deliberately limited to what Vision Studio knows: the product's own metadata
 * and the vision engine's findings. There is no price, no discount, no
 * inventory — this application does not model commerce.
 */
export const TEMPLATE_VARIABLES = [
  { key: '{{product_name}}', label: 'Product name', example: 'Ribbed Knit Midi Dress' },
  { key: '{{category}}', label: 'Category', example: 'Dresses' },
  { key: '{{folder}}', label: 'Source folder', example: 'AW25/dresses' },
  { key: '{{file_name}}', label: 'File name', example: 'look-01.jpg' },
  { key: '{{shot_type}}', label: 'Detected shot type', example: 'full_body' },
  { key: '{{garment_type}}', label: 'Detected garment type', example: 'full_outfit' },
  { key: '{{index}}', label: 'Image index within product', example: '1' },
] as const

export interface TemplateVariableValues {
  product_name: string
  category: string
  folder: string
  file_name: string
  shot_type: string
  garment_type: string
  index: string
}

export function resolveTemplateVariables(
  content: string,
  values: Partial<TemplateVariableValues>
): string {
  return content.replace(/\{\{(\w+)\}\}/g, (match, key: string) => {
    const value = (values as Record<string, string | undefined>)[key]
    return value ?? match
  })
}

// ─── Layer factories ─────────────────────────────────────────────────────────

let layerCounter = 0
function nextLayerId(): string {
  // Not cryptographic — layer ids only need to be unique within a document.
  layerCounter += 1
  return `layer_${Date.now().toString(36)}_${layerCounter.toString(36)}`
}

export function createLayer(type: LayerType, zIndex: number): Layer {
  const base: BaseLayer = {
    id: nextLayerId(),
    type,
    name: type.charAt(0).toUpperCase() + type.slice(1),
    x: 10,
    y: 10,
    width: 40,
    height: 12,
    rotation: 0,
    opacity: 1,
    zIndex,
    visible: true,
    locked: false,
    anchorTo: null,
  }

  switch (type) {
    case 'text':
      return {
        ...base,
        type: 'text',
        name: 'Text',
        content: '{{product_name}}',
        fontFamily: 'Inter',
        fontSizePct: 4,
        fontWeight: 'bold',
        color: '#111111',
        align: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        wrap: true,
        backgroundColor: null,
        paddingPct: 0,
        borderRadiusPct: 0,
        uppercase: false,
      }
    case 'image':
      return {
        ...base,
        type: 'image',
        name: 'Image',
        assetKey: '',
        fit: 'contain',
        borderRadiusPct: 0,
      }
    case 'rectangle':
      return {
        ...base,
        type: 'rectangle',
        name: 'Rectangle',
        fill: '#111111',
        borderRadiusPct: 0,
        strokeColor: null,
        strokeWidthPct: 0,
      }
    case 'ellipse':
      return {
        ...base,
        type: 'ellipse',
        name: 'Ellipse',
        width: 20,
        height: 20,
        fill: '#111111',
        strokeColor: null,
        strokeWidthPct: 0,
      }
    case 'badge':
      return {
        ...base,
        type: 'badge',
        name: 'Badge',
        width: 22,
        height: 7,
        content: 'NEW IN',
        fill: '#111111',
        color: '#ffffff',
        fontFamily: 'Inter',
        fontSizePct: 2.4,
        fontWeight: 'bold',
        shape: 'pill',
        uppercase: true,
      }
  }
}
